project:
  type: website
  output-dir: ../docs


website:
  title: "Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes-2023-05-09.qmd
        text: Workshop thoughts
      - href: about.qmd
        text: About the instructor

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

